version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 3001:27017
    volumes:
      - ./dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
